import { Item, OrderItem } from "@/app/types/commonTypes";
import slugify from "slugify";
export const tags = {
  pardha: "Pardha",
  blue: "Blue",
  black: "Black",
  maxi: "Maxi",
  fullSleeveMaxi: "Full Sleeve",
  latest: "Latest",
};
export const itemData: Item[] = [
  {
    id: slugify("Skinny Umberlla Pardha Blue XL",{lower:true}),
    groupId: 1,
    name: "Skinny Umberlla Pardha Blue XL",
    brand: "Test",
    tags: [tags.pardha, tags.blue, tags.latest],
    description: "Blue large Pardha",
    size: "XL",
    color: "Blue",
    discount: 10,
    inventory: 10,
    price: 800,
    images: [
      "https://picsum.photos/400",
      "https://picsum.photos/406",
      "https://picsum.photos/407",
    ],
    date: "28/04/2024",
    features: ["100% Cotton", "Ultra Soft Fabric", "Tailored Fit Sizes"],
  },
  {
    id: slugify("Skinny Umberlla Pardha Black Large",{lower:true}),
    groupId: 1,
    name: "Skinny Umberlla Pardha Black Large",
    brand: "Test",
    tags: [tags.pardha, tags.blue, tags.latest],
    description: "Black large Pardha",
    size: "L",
    color: "Black",
    discount: 0,
    inventory: 5,
    price: 800,
    images: ["https://picsum.photos/401"],
    date: "28/04/2024",
    features: ["100% Cotton", "Ultra Soft Fabric", "Tailored Fit Sizes"],
  },
  {
    id: slugify("Check Maxi Blue Large",{lower:true}),
    groupId: 2,
    name: "Check Maxi Blue Large",
    brand: "Slag",
    tags: [tags.maxi, tags.blue, tags.latest],
    description: "Blue large Pardha",
    size: "L",
    color: "Blue",
    discount: 0,
    inventory: 5,
    price: 800,
    images: ["https://picsum.photos/402"],
    date: "28/04/2024",
  },
  {
    id: slugify("Skinny Umberlla Pardha Black XL",{lower:true}),
    groupId: 1,
    name: "Skinny Umberlla Pardha Black XL",
    brand: "Black",
    tags: [tags.pardha, tags.blue, tags.latest],
    description: "Black large Pardha",
    size: "XL",
    color: "Black",
    discount: 10,
    inventory: 10,
    price: 800,
    images: ["https://picsum.photos/400", "https://picsum.photos/406"],
    date: "28/04/2024",
  },
  {
    id: slugify("Skinny Umberlla Pardha Blue Large",{lower:true}),
    groupId: 1,
    name: "Skinny Umberlla Pardha  Blue Large",
    brand: "Test",
    tags: [tags.pardha, tags.blue, tags.latest],
    description: "Blue large Pardha",
    size: "L",
    color: "Blue",
    discount: 0,
    inventory: 5,
    price: 800,
    images: ["https://picsum.photos/401"],
    date: "28/04/2024",
  },
  {
    id: slugify("Check Maxi Black Large",{lower:true}),
    groupId: 2,
    name: "Check Maxi Black Large",
    brand: "Slag",
    tags: [tags.maxi, tags.black],
    description: "Blue large Pardha",
    size: "L",
    color: "Black",
    discount: 0,
    inventory: 5,
    price: 800,
    images: ["https://picsum.photos/402"],
    date: "28/04/2024",
  },
  {
    id: slugify("Check Maxi Black XL",{lower:true}),
    groupId: 2,
    name: "Check Maxi Black XL",
    brand: "Slag",
    tags: [tags.maxi, tags.black],
    description: "Blue large Pardha",
    size: "XL",
    color: "Blue",
    discount: 0,
    inventory: 5,
    price: 800,
    images: ["https://picsum.photos/402"],
    date: "28/04/2024",
  },
];

export const orderItem: OrderItem[] = [
  {
    itemID: slugify("Skinny Umberlla Pardha Blue XL",{lower:true}),
    dateAdded: "02/05/2025",
    quantity: 2,
  },
  {
    itemID: slugify("Skinny Umberlla Pardha Black Large",{lower:true}),
    dateAdded: "02/02/2025",
    quantity: 1,
  },
];
